#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="data")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void Insertchanpin(chanpin instance);
  partial void Updatechanpin(chanpin instance);
  partial void Deletechanpin(chanpin instance);
  partial void Insertguke(guke instance);
  partial void Updateguke(guke instance);
  partial void Deleteguke(guke instance);
  partial void Insertdingdan(dingdan instance);
  partial void Updatedingdan(dingdan instance);
  partial void Deletedingdan(dingdan instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["data"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<chanpin> chanpin
	{
		get
		{
			return this.GetTable<chanpin>();
		}
	}
	
	public System.Data.Linq.Table<guke> guke
	{
		get
		{
			return this.GetTable<guke>();
		}
	}
	
	public System.Data.Linq.Table<dingdan> dingdan
	{
		get
		{
			return this.GetTable<dingdan>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chanpin")]
public partial class chanpin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _cpid;
	
	private string _cpmc;
	
	private int _cpsl;
	
	private string _cpjs;
	
	private string _cptp;
	
	private int _cpdj;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncpidChanging(int value);
    partial void OncpidChanged();
    partial void OncpmcChanging(string value);
    partial void OncpmcChanged();
    partial void OncpslChanging(int value);
    partial void OncpslChanged();
    partial void OncpjsChanging(string value);
    partial void OncpjsChanged();
    partial void OncptpChanging(string value);
    partial void OncptpChanged();
    partial void OncpdjChanging(int value);
    partial void OncpdjChanged();
    #endregion
	
	public chanpin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpid", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int cpid
	{
		get
		{
			return this._cpid;
		}
		set
		{
			if ((this._cpid != value))
			{
				this.OncpidChanging(value);
				this.SendPropertyChanging();
				this._cpid = value;
				this.SendPropertyChanged("cpid");
				this.OncpidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpmc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string cpmc
	{
		get
		{
			return this._cpmc;
		}
		set
		{
			if ((this._cpmc != value))
			{
				this.OncpmcChanging(value);
				this.SendPropertyChanging();
				this._cpmc = value;
				this.SendPropertyChanged("cpmc");
				this.OncpmcChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpsl", DbType="Int NOT NULL")]
	public int cpsl
	{
		get
		{
			return this._cpsl;
		}
		set
		{
			if ((this._cpsl != value))
			{
				this.OncpslChanging(value);
				this.SendPropertyChanging();
				this._cpsl = value;
				this.SendPropertyChanged("cpsl");
				this.OncpslChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpjs", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string cpjs
	{
		get
		{
			return this._cpjs;
		}
		set
		{
			if ((this._cpjs != value))
			{
				this.OncpjsChanging(value);
				this.SendPropertyChanging();
				this._cpjs = value;
				this.SendPropertyChanged("cpjs");
				this.OncpjsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cptp", DbType="NVarChar(50)")]
	public string cptp
	{
		get
		{
			return this._cptp;
		}
		set
		{
			if ((this._cptp != value))
			{
				this.OncptpChanging(value);
				this.SendPropertyChanging();
				this._cptp = value;
				this.SendPropertyChanged("cptp");
				this.OncptpChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpdj", DbType="Int NOT NULL")]
	public int cpdj
	{
		get
		{
			return this._cpdj;
		}
		set
		{
			if ((this._cpdj != value))
			{
				this.OncpdjChanging(value);
				this.SendPropertyChanging();
				this._cpdj = value;
				this.SendPropertyChanged("cpdj");
				this.OncpdjChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.guke")]
public partial class guke : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _zhid;
	
	private string _name;
	
	private string _pwd;
	
	private string _phone;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnzhidChanging(string value);
    partial void OnzhidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
	
	public guke()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zhid", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string zhid
	{
		get
		{
			return this._zhid;
		}
		set
		{
			if ((this._zhid != value))
			{
				this.OnzhidChanging(value);
				this.SendPropertyChanging();
				this._zhid = value;
				this.SendPropertyChanged("zhid");
				this.OnzhidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string pwd
	{
		get
		{
			return this._pwd;
		}
		set
		{
			if ((this._pwd != value))
			{
				this.OnpwdChanging(value);
				this.SendPropertyChanging();
				this._pwd = value;
				this.SendPropertyChanged("pwd");
				this.OnpwdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dingdan")]
public partial class dingdan : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ddid;
	
	private string _cpmc;
	
	private int _gmsl;
	
	private System.DateTime _gmsj;
	
	private string _zhid;
	
	private string _dizhi;
	
	private string _phone;
	
	private string _cpid;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnddidChanging(string value);
    partial void OnddidChanged();
    partial void OncpmcChanging(string value);
    partial void OncpmcChanged();
    partial void OngmslChanging(int value);
    partial void OngmslChanged();
    partial void OngmsjChanging(System.DateTime value);
    partial void OngmsjChanged();
    partial void OnzhidChanging(string value);
    partial void OnzhidChanged();
    partial void OndizhiChanging(string value);
    partial void OndizhiChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OncpidChanging(string value);
    partial void OncpidChanged();
    #endregion
	
	public dingdan()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ddid", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ddid
	{
		get
		{
			return this._ddid;
		}
		set
		{
			if ((this._ddid != value))
			{
				this.OnddidChanging(value);
				this.SendPropertyChanging();
				this._ddid = value;
				this.SendPropertyChanged("ddid");
				this.OnddidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpmc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string cpmc
	{
		get
		{
			return this._cpmc;
		}
		set
		{
			if ((this._cpmc != value))
			{
				this.OncpmcChanging(value);
				this.SendPropertyChanging();
				this._cpmc = value;
				this.SendPropertyChanged("cpmc");
				this.OncpmcChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gmsl", DbType="Int NOT NULL")]
	public int gmsl
	{
		get
		{
			return this._gmsl;
		}
		set
		{
			if ((this._gmsl != value))
			{
				this.OngmslChanging(value);
				this.SendPropertyChanging();
				this._gmsl = value;
				this.SendPropertyChanged("gmsl");
				this.OngmslChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gmsj", DbType="Date NOT NULL")]
	public System.DateTime gmsj
	{
		get
		{
			return this._gmsj;
		}
		set
		{
			if ((this._gmsj != value))
			{
				this.OngmsjChanging(value);
				this.SendPropertyChanging();
				this._gmsj = value;
				this.SendPropertyChanged("gmsj");
				this.OngmsjChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zhid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string zhid
	{
		get
		{
			return this._zhid;
		}
		set
		{
			if ((this._zhid != value))
			{
				this.OnzhidChanging(value);
				this.SendPropertyChanging();
				this._zhid = value;
				this.SendPropertyChanged("zhid");
				this.OnzhidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dizhi", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string dizhi
	{
		get
		{
			return this._dizhi;
		}
		set
		{
			if ((this._dizhi != value))
			{
				this.OndizhiChanging(value);
				this.SendPropertyChanging();
				this._dizhi = value;
				this.SendPropertyChanged("dizhi");
				this.OndizhiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpid", DbType="NVarChar(50)")]
	public string cpid
	{
		get
		{
			return this._cpid;
		}
		set
		{
			if ((this._cpid != value))
			{
				this.OncpidChanging(value);
				this.SendPropertyChanging();
				this._cpid = value;
				this.SendPropertyChanged("cpid");
				this.OncpidChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
